//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public int ID { get; set; }
        public string ContactId { get; set; }
        public int IsDelete { get; set; }
        public string Account { get; set; }
        public string ContactName { get; set; }
        public string CommonMobile { get; set; }
        public string HeadPortrait { get; set; }
        public string AttFile { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual GroupInfo GroupInfo { get; set; }
    }
}
