//------------------------------------------------------------------------------
// <auto-generated>

namespace MVC.Model
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ContactInfoView
    {
        [DisplayName("编号")]
        public int ID { get; set; }
        public string ContactId { get; set; }
        public int IsDelete { get; set; }
        public string Account { get; set; }
        [DisplayName("名称"), Required(ErrorMessage = "名称非空")]
        public string ContactName { get; set; }
        [DisplayName("电话"), Required(ErrorMessage = "电话非空")]
        public string CommonMobile { get; set; }
        public string HeadPortrait { get; set; }
        public string AttFile { get; set; }
        [DisplayName("所属分组")]
        public Nullable<int> GroupId { get; set; }

        public virtual GroupInfoView GroupInfo { get; set; }
    }
}
