//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。

namespace MVC.Model
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class GroupInfoView
    {
        public int GroupId { get; set; }
         public string GroupName { get; set; }

        public virtual ICollection<ContactInfoView> ContactInfoes { get; set; }
    }
}
